function initGUI(obj)
%INITGUI Initialize interactive GUI for exploring multi-channel EMG

if isempty(obj.Data)
    error('No Data loaded. Call loadSignal() before initGUI().');
end

nCh = size(obj.Data,1);
% Compute vertical offset per channel
offsetVec = obj.Spacing * (nCh:-1:1);


% Create figure and axes
if isempty(obj.Figure) || ~isvalid(obj.Figure)
    obj.Figure = figure('Name', 'MUExplorer', ...
        'Color', 'w', ...
        'KeyPressFcn', @(src, evt) obj.keyHandler(evt), ...
        'KeyReleaseFcn', @(src, evt) obj.keyReleaseHandler(evt), ...
        'WindowButtonDownFcn', @(src, evt) obj.clickCallback(), ...
        'WindowButtonMotionFcn', @(src, evt) obj.updatePointer(), ...
        'WindowButtonUpFcn', @(src, evt) obj.releaseCallback(), ...
        'WindowScrollWheelFcn', @(src, evt) obj.handleScroll(evt), ...
        'Units', 'normalized', ...
        'MenuBar', 'none', 'ToolBar', 'none', ...
        'Position', [0.05 0.1 0.9 0.8], ...
        'DeleteFcn', @obj.delete);

    % Create metadata panel on the left
    obj.MetaPanel = uipanel(obj.Figure, ...
        'Title', 'MUExplorer', ...
        'FontWeight', 'bold', ...
        'FontSize', 20, ...
        'BackgroundColor', 'k', ...
        'ForegroundColor', 'w', ...
        'Units', 'normalized', ...
        'Position', [0.01 0.41 0.2 0.55]);  % 25% width

    % Create main layout (for EMG + convolution) on the right
    obj.MainLayout = tiledlayout(obj.Figure, 4, 1);
    obj.MainLayout.Units = 'normalized';
    obj.MainLayout.Position = [0.27 0.05 0.72 0.9];  % 72% width
    obj.MainLayout.TileSpacing = 'compact';
    obj.MainLayout.Padding = 'compact';

    % Add metadata text fields
    obj.MetaTextHandles.TemplateInfo = uicontrol(obj.MetaPanel, ...
        'Style', 'text', 'ForegroundColor', 'w', 'BackgroundColor', 'k',  ...
        'String', 'Template: 1 / N', ...
        'Units', 'normalized', 'Position', [0.01 0.75 0.98 0.15], ...
        'FontSize', 16, 'HorizontalAlignment', 'center');
    
    obj.MetaTextHandles.SpikeCount = uicontrol(obj.MetaPanel, ...
        'Style', 'text', 'ForegroundColor', 'w', 'BackgroundColor', 'k',  ...
        'String', 'Spikes: 0', ...
        'Units', 'normalized', 'Position', [0.01 0.55 0.98 0.15], ...
        'FontSize', 16, 'HorizontalAlignment', 'center');
    
    obj.MetaTextHandles.Instructions = uicontrol(obj.MetaPanel, ...
        'Style', 'text', 'ForegroundColor', 'w', 'BackgroundColor', 'k',  ...
        'String', 'Press [H] for help, [Click] to add spike.', ...
        'Units', 'normalized', ...
        'Position', [0.01 0.05 0.98 0.45], ...
        'FontSize', 12, ...
        'FontName', 'Consolas', ...
        'HorizontalAlignment', 'left');

    % --- Row 2: Main EMG plot ---
    obj.MainAxes = nexttile(obj.MainLayout,1,[3 1]);
    set(obj.MainAxes,'NextPlot','add','ColorOrder',obj.ColorOrder);
    obj.ConvAxes = nexttile(obj.MainLayout,4,[1 1]);
    set(obj.ConvAxes,'NextPlot','add','ColorOrder',[0 0 0; 1 0 0],'YLim',[0 1],'YColor','none');
    obj.ConvMatchLbLine = yline(obj.ConvAxes,obj.ConvMatchLim(obj.CurrentTemplateIndex,1), ...
        'Color', [0.35 0.35 0.85], 'LineWidth', 0.5, 'LineStyle', '--', 'HitTest', 'off');
    obj.ConvMatchUbLine = yline(obj.ConvAxes,obj.ConvMatchLim(obj.CurrentTemplateIndex,2),...
        'Color',[0.85 0.35 0.35], 'LineWidth', 0.5, 'LineStyle', '--', 'HitTest', 'off');

    linkaxes([obj.MainAxes,obj.ConvAxes],'x');

    obj.TemplateInsetAxes = axes(obj.Figure, ...
        'NextPlot','add','XColor','none','YColor','none', ...
        'Units','normalized', 'ColorOrder', obj.ColorOrder, ...
        'Position', [0.05 0.05 0.125 0.3], ...
        'XLim',[0 1], 'YLim',[0 1]);

    % Overlay reference signal
    if ~isempty(obj.PathTrace)
        yy = obj.PathTrace * obj.Spacing * 0.25 * nCh + obj.Spacing*0.1*nCh;
        obj.PathTraceHandle = plot(obj.MainAxes, obj.Time, yy, 'LineStyle','-',...
            'Color', [0.65 0.65 0.65], 'LineWidth', 2, ...
            'HitTest','off');
    end
    if ~isempty(obj.Sync)
        yy = obj.Sync * 0.2 * obj.Spacing * nCh + 0.75*obj.Spacing*nCh;
        obj.SyncTraceHandle = plot(obj.MainAxes, obj.Time, yy, 'LineStyle', '-', ...
            'Color', [0.35 0.35 0.35], 'LineWidth', 2, ...
            'HitTest', 'off');
    end
    % Plot EMG traces
    obj.PlotHandles = gobjects(nCh,1);
    for ch = 1:nCh
        y = obj.Data(ch,:) + offsetVec(ch);
        obj.PlotHandles(ch) = plot(obj.MainAxes, obj.Time, y,'LineWidth', 0.5);
    end
    
    % Plot placeholders for selected peak markers
    obj.MarkerHandles = plot(obj.MainAxes, NaN, NaN(1,nCh), 'ro', 'MarkerSize', 6, 'LineWidth', 1.5);
else
    figure(obj.Figure);
end

% Set limits
xlim(obj.MainAxes, [0 obj.Time(end)]);
ylim(obj.MainAxes, [min(offsetVec)-obj.Spacing, max(offsetVec)+obj.Spacing]);
obj.OriginalXLim = xlim(obj.MainAxes);
obj.OriginalYLim = ylim(obj.MainAxes);

% --- Row 3: Convolution trace ---
title(obj.ConvAxes, 'Matched Filter Output');
xlabel(obj.ConvAxes, 'Time (s)');
ylabel(obj.ConvAxes, 'Score');

if obj.GuiReady
    obj.loadResults();
end
obj.GuiReady = true;
end